version: "3.8"

services:
  tagging-service:
    image: navchetna/tagging-service:latest
    container_name: tagging-service
    ports:
      - "8000:8000"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"

      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_BASE: "${OPENAI_API_BASE}"
      MODEL_NAME: "meta-llama/Llama-3.1-8B-Instruct"

      GROQ_API_KEY: "${GROQ_API_KEY}"
      GROQ_MODEL: "llama-3.3-70b-versatile"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
networks:
  default:
    driver: bridge