apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup
  namespace: vector-db
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: provisioner
          containers:
          - name: cleanup
            image: navchetna/vector-db-cleanup:latest
            env:
            - name: NAMESPACE
              value: "vector-db"
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure
